spring.application.name=ClimedOnBoard
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key


# Configuração do servidor
server.port=8090

# Configuração do banco de dados MySQL
spring.datasource.url=jdbc:mysql://192.168.0.115:3306/climedboard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=JRPBJR
spring.datasource.password=Zeeze@5775

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true